---
# tasks file for jenkins
- name: Import Jenkins GPG key
  rpm_key:
      state: present
      key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
      debugger: on_failed
- name: Add Jenkins repository
  yum_repository:
      name: jenkins
      description: jenkins repository
      baseurl: http://pkg.jenkins.io/redhat
      enabled: no
      gpgcheck: yes 
      debugger: on_failed
- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present
    debugger: on_failed
- name: Start Jenkins
  service: 
    name: jenkins-2.45
    enabled: yes
    state: restarted
    debugger: on_failed

       
